# --- Full contents of every kv/apps/* secret object this root reconciles.
# Some fields are arbitrary (Terraform could generate them) and some are
# externally issued (GitHub App/OAuth credentials) — both kinds live in these
# same maps, one variable per KV object, because that's the natural unit of
# "what's this secret" and it matches the object Vault itself stores. Never
# committed — populated in a gitignored local.auto.tfvars.

# The argocd/envoy/grafana/openbao client secrets in this same KV object are
# arbitrary (Dex<->client shared secrets) — Terraform generates and owns
# those directly (random_password resources in main.tf), no variable needed.
# Only Dex's GitHub *connector* credentials (its upstream IdP, unrelated to
# the client-secret axis above) are external — issued by GitHub's own OAuth
# App registration, can't be regenerated by Terraform.
variable "dex_github_connector" {
  description = "github-client-id/github-client-secret fields of kv/apps/dex/credentials (Dex's GitHub connector)."
  type        = map(string)
  sensitive   = true
}

# privateKey.pem is the GitHub App's private key, downloaded from GitHub —
# external, not generatable.
variable "secrets_sync_github_eso_private_key" {
  description = "Full contents of kv/apps/secrets-sync/github/eso-github-app-private-key."
  type        = map(string)
  sensitive   = true
}

# Structured so the scope of each secret is explicit in code, not just
# encoded as an opaque KV path string — a GitHub repo/environment rename is a
# map-key rename here, not a hunt through hardcoded path segments.
# Mirrors the gitops repo's apps/secrets-sync/values.yaml `targets` shape
# (global org-wide secrets vs per-repo vs per-repo-per-environment), though
# that chart's `targets[].repository`/`.environment` still need updating too
# on a rename — these are two independent systems kept in sync by convention.
#
#   global                        -> kv/apps/secrets-sync/github/global
#   repos["<repo>"].secrets        -> kv/apps/secrets-sync/github/<repo>
#   repos["<repo>"].environments["<env>"] -> kv/apps/secrets-sync/github/<repo>-<env>
#
# SCW_ACCESS_KEY/SCW_SECRET_KEY under repos.infrastructure.environments.scaleway
# are NOT supplied here — main.tf merges those in from
# data.terraform_remote_state.dns_scaleway instead.
variable "secrets_sync_github" {
  description = "GitHub secrets-sync content (kv/apps/secrets-sync/github/*), scoped by org/repo/repo+environment."
  type = object({
    global = optional(map(string), {})
    repos = optional(map(object({
      secrets      = optional(map(string), {})
      environments = optional(map(map(string)), {})
    })), {})
  })
  sensitive = true
}
