# --- Full contents of every kv/apps/* secret object this root reconciles.
# Some fields are arbitrary (Terraform could generate them) and some are
# externally issued (GitHub App/OAuth credentials) — both kinds live in these
# same maps, one variable per KV object, because that's the natural unit of
# "what's this secret" and it matches the object Vault itself stores. Never
# committed — populated in a gitignored local.auto.tfvars.

# The argocd/envoy/grafana/openbao client secrets in this same KV object are
# arbitrary (Dex<->client shared secrets) — Terraform generates and owns
# those directly (random_password resources in main.tf), no variable needed.
# Only Dex's GitHub *connector* credentials (its upstream IdP, unrelated to
# the client-secret axis above) are external — issued by GitHub's own OAuth
# App registration, can't be regenerated by Terraform.
variable "dex_github_connector" {
  description = "github-client-id/github-client-secret fields of kv/apps/dex/credentials (Dex's GitHub connector)."
  type        = map(string)
  sensitive   = true
}

# Mirrors 10-cluster/scaleway's var.letsencrypt_staging (see that variable's
# own comment for the full "why") -- kept as an independent variable in this
# root rather than a cross-root terraform_remote_state read of that one,
# same "two roots' TEMPORARY overrides kept manually in sync" pattern this
# flag already used historically (see git history: 98f87ce/74e37e4 added
# rootCA/oidc_discovery_ca_pem together across both repos, 8fc3c74/3ff54d4
# removed them together). Only consumed by vault_jwt_auth_backend.oidc's own
# oidc_discovery_ca_pem below -- OpenBao's pod itself needs no CA/volume/init
# container changes at all, since this field lets OpenBao trust a CA for
# just this one auth backend's own outbound OIDC discovery call, entirely
# server-side, independent of the pod's system trust store.
variable "letsencrypt_staging" {
  type        = bool
  default     = false
  description = "Use Let's Encrypt staging's root CA for OpenBao's own OIDC discovery call to auth.scalepack.fr (vault_jwt_auth_backend.oidc), matching 10-cluster/scaleway's var.letsencrypt_staging when that root's gateway-config runs letsencrypt-staging instead of letsencrypt-prod."
}

# privateKey.pem is the GitHub App's private key, downloaded from GitHub —
# external, not generatable.
variable "secrets_sync_github_eso_private_key" {
  description = "Full contents of kv/apps/secrets-sync/github/eso-github-app-private-key."
  type        = map(string)
  sensitive   = true
}

# Structured so the scope of each secret is explicit in code, not just
# encoded as an opaque KV path string — a GitHub repo/environment rename is a
# map-key rename here, not a hunt through hardcoded path segments.
# Mirrors the gitops repo's apps/secrets-sync/values.yaml `targets` shape
# (global org-wide secrets vs per-repo vs per-repo-per-environment), though
# that chart's `targets[].repository`/`.environment` still need updating too
# on a rename — these are two independent systems kept in sync by convention.
#
#   global                        -> kv/apps/secrets-sync/github/global
#   repos["<repo>"].secrets        -> kv/apps/secrets-sync/github/<repo>
#   repos["<repo>"].environments["<env>"] -> kv/apps/secrets-sync/github/<repo>-<env>
#
# SCW_ACCESS_KEY/SCW_SECRET_KEY under repos.infrastructure.environments.scaleway
# are NOT supplied here — main.tf merges those in from
# data.terraform_remote_state.dns_scaleway instead. WireGuard's keys are the
# same story: read straight from data.terraform_remote_state.wireguard, no
# variable needed.

variable "secrets_sync_github" {
  description = "GitHub secrets-sync content (kv/apps/secrets-sync/github/*), scoped by org/repo/repo+environment."
  type = object({
    global = optional(map(string), {})
    repos = optional(map(object({
      secrets      = optional(map(string), {})
      environments = optional(map(map(string)), {})
    })), {})
  })
  sensitive = true
}

# See version.tf's provider "vault" block for the three real addresses this
# resolves to (in-cluster Service / port-forward / public route) and which
# execution context uses each.
variable "vault_address" {
  description = "Address the vault provider authenticates against."
  type        = string
  default     = "http://openbao.openbao.svc:8200/"
}

# ── Cross-root state reads (Scaleway state buckets, see 00-foundation/scaleway) ──

variable "dns_scaleway_state_bucket" {
  description = "Scaleway bucket holding 01-iam/workload/scaleway's remote state."
  type        = string
}
variable "dns_scaleway_state_key" {
  description = "Object key for 01-iam/workload/scaleway's state within dns_scaleway_state_bucket."
  type        = string
}

variable "backup_scaleway_state_bucket" {
  description = "Scaleway bucket holding 03-storage/scaleway's remote state."
  type        = string
}
variable "backup_scaleway_state_key" {
  description = "Object key for 03-storage/scaleway's state within backup_scaleway_state_bucket."
  type        = string
}

variable "wireguard_state_bucket" {
  description = "Scaleway bucket holding 04-vpn/wireguard-site-to-site's remote state."
  type        = string
}
variable "wireguard_state_key" {
  description = "Object key for 04-vpn/wireguard-site-to-site's state within wireguard_state_bucket."
  type        = string
}

variable "wireguard_exit_state_bucket" {
  description = "Scaleway bucket holding 04-vpn/wireguard-exit's remote state."
  type        = string
}
variable "wireguard_exit_state_key" {
  description = "Object key for 04-vpn/wireguard-exit's state within wireguard_exit_state_bucket."
  type        = string
}

variable "openbao_bootstrap_state_bucket" {
  description = "Scaleway bucket holding 11-secrets/openbao/bootstrap's remote state."
  type        = string
}
variable "openbao_bootstrap_state_key" {
  description = "Object key for 11-secrets/openbao/bootstrap's state within openbao_bootstrap_state_bucket."
  type        = string
}

variable "iam_bootstrap_scaleway_state_bucket" {
  description = "Scaleway bucket holding 01-iam/bootstrap/scaleway's remote state."
  type        = string
}
variable "iam_bootstrap_scaleway_state_key" {
  description = "Object key for 01-iam/bootstrap/scaleway's state within iam_bootstrap_scaleway_state_bucket."
  type        = string
}

variable "foundation_scaleway_state_bucket" {
  description = "Scaleway bucket holding 00-foundation/scaleway's own remote state (read for its access_keys/secret_keys outputs -- the per-state-bucket dedicated identities)."
  type        = string
}
variable "foundation_scaleway_state_key" {
  description = "Object key for 00-foundation/scaleway's state within foundation_scaleway_state_bucket."
  type        = string
}
